### ISSUE TITLE
Pretrained weights for UDG task?

### ISSUE THREAD

**Issue by Wonder1905** [leokarlin/BrAD#2]
Hi, can you release the Resnet18 pretrained weights on Pacs dataset for UDG task? 
Thanks!

**Comment by EliSchwartz** [comment]
The pretrained models for UDG on DomainNet are available here https://www.dropbox.com/sh/9vi2es8ycfobawd/AADRtWUCZEXsJ0PFcJg37srka?dl=0

source-PRS means the source domains are Painting, Real & Sketch.
source-CIQ means the source domains are Clipart, Infograph & Quickdraw.

**Comment by workerbcd** [comment]
Hi,

Have you reproduced their results on DomainNet with these two released models?

**Comment by JizeZhangPsych** [comment]
> Hi, can you release the Resnet18 pretrained weights on Pacs dataset for UDG task?
> Thanks!

@Wonder1905
Could you reproduce the result in Table 1 with the given weights? I modified the main_brad_test.py but the acc is only ~17% rather than 60.78%
