### ISSUE TITLE
About the FUDA training script.

### ISSUE THREAD

**Issue by Bostoncake** [leokarlin/BrAD#3]
Hi! I am very appreciated of your work and it really inspires me. I am trying to reproduce the results in Table 3 of your paper. However, I couldn't find the training script and parameters in your official README. Would you please share the FUDA training parameters and scripts so that I could reproduce your results?

Thank you!

**Comment by EliSchwartz** [comment]
The instructions in the README (training and testing) are for the FUDA setup. The default parameters should reproduce the results.
